info:
  contact: {}
paths:
  /admin/category-create:
    post:
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类名称
        in: formData
        name: name
        required: true
        type: string
      - description: parentId
        in: formData
        name: parentId
        type: integer
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 创建分类列表
      tags:
      - 私有方法
  /admin/category-delete:
    delete:
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 修改分类列表
      tags:
      - 私有方法
  /admin/category-list:
    get:
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请输入当前页数,默认第一页
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 分类列表
      tags:
      - 私有方法
  /admin/category-update:
    put:
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: parentId
        in: formData
        name: parentId
        type: integer
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: 分类名称
        in: formData
        name: name
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 修改分类列表
      tags:
      - 私有方法
  /admin/problem-create:
    post:
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        required: true
        type: integer
      - description: max_mem
        in: formData
        name: max_mem
        required: true
        type: integer
      - collectionFormat: multi
        description: 标签
        in: formData
        items:
          type: string
        name: category_ids
        type: array
      - collectionFormat: multi
        description: test_cases
        in: formData
        items:
          type: string
        name: test_cases
        required: true
        type: array
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 创建问题
      tags:
      - 私有方法
  /admin/problem-update:
    put:
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        required: true
        type: integer
      - description: max_mem
        in: formData
        name: max_mem
        required: true
        type: integer
      - collectionFormat: multi
        description: 标签
        in: formData
        items:
          type: string
        name: category_ids
        type: array
      - collectionFormat: multi
        description: test_cases
        in: formData
        items:
          type: string
        name: test_cases
        required: true
        type: array
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 修改问题
      tags:
      - 私有方法
  /login:
    post:
      parameters:
      - description: 用户名
        in: formData
        name: username
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /problem-detail:
    get:
      parameters:
      - description: identity
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 问题详情
      tags:
      - 公共方法
  /problem-list:
    get:
      parameters:
      - description: 请输入当前页数,默认第一页
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: category_identity
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
  /rank-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 用户排行榜
      tags:
      - 公共方法
  /register:
    post:
      parameters:
      - description: 电子邮箱
        in: formData
        name: mail
        required: true
        type: string
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 验证码
        in: formData
        name: code
        required: true
        type: string
      - description: 手机
        in: formData
        name: phone
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
  /send-code:
    post:
      parameters:
      - description: 电子邮箱
        in: formData
        name: email
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 发送邮箱验证码
      tags:
      - 公共方法
  /submit-list:
    get:
      parameters:
      - description: 请输入当前页数,默认第一页
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: 'problem_identity '
        in: query
        name: problem_identity
        type: string
      - description: user_identity
        in: query
        name: user_identity
        type: string
      - description: status
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 提交列表
      tags:
      - 公共方法
  /user-detail:
    get:
      parameters:
      - description: identity
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 公共方法
  /user/submit:
    post:
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: problem_identity
        in: query
        name: problem_identity
        required: true
        type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 代码提交
      tags:
      - 用户私有方法
swagger: "2.0"
